# Generated by Django 4.2.13 on 2024-08-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='profile_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendships_initiated', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='profile_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendships_received', to='main.profile'),
        ),
    ]
