# Generated by Django 4.2.13 on 2024-08-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_friendship_profile_one_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendshipStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.AlterField(
            model_name="friendship",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.friendshipstatus"
            ),
        ),
    ]
