# Generated by Django 4.2.13 on 2024-08-27 13:45

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_mediafile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='main.interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.ForeignKey(default=main.models.get_default_privacy_level, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.privacylevel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
