# Generated by Django 4.2.13 on 2024-09-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_age_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archived_replies', to='main.archivedmail')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_received_messages', to='main.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_sent_messages', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_chat_members', to='main.group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_chat_messages', to='main.profile')),
            ],
        ),
    ]
