# Generated by Django 4.2.13 on 2024-08-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_profile_age"),
        ("main", "0009_alter_profile_age_alter_profile_gender_and_more"),
    ]

    operations = []
