# Generated by Django 4.2.13 on 2024-09-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_archivedmail_archivechat"),
        ("main", "0010_merge_20240829_1832"),
    ]

    operations = []
