# Generated by Django 4.2.13 on 2024-09-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20240903_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmail',
            name='is_deleted_sender',
            field=models.BooleanField(default=False),
        ),
    ]
