# Generated by Django 4.2.13 on 2024-09-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_archivedmail_is_deleted_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
