# Generated by Django 4.2.13 on 2024-09-08 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification_norest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATION", "AUTHENTICATION"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_notifications",
                        to="main.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog_norest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("NEWS", "NEWS"),
                            ("GROUP", "GROUP"),
                            ("PROFILE", "PROFILE"),
                            ("MAIL", "MAIL"),
                            ("FRIEND", "FRIEND"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_activities",
                        to="main.profile",
                    ),
                ),
            ],
        ),
    ]
